/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * The version of the OpenAPI document: 1.0\"
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ow2.proactive.catalog.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ow2.proactive.catalog.client.model.Link;
import org.ow2.proactive.catalog.client.model.ModificationHistoryData;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.ow2.proactive.catalog.client.JSON;


/**
 * BucketGrantMetadata
 */
@JsonPropertyOrder({
  BucketGrantMetadata.JSON_PROPERTY_GRANTEE_TYPE,
  BucketGrantMetadata.JSON_PROPERTY_GRANTEE,
  BucketGrantMetadata.JSON_PROPERTY_ACCESS_TYPE,
  BucketGrantMetadata.JSON_PROPERTY_PRIORITY,
  BucketGrantMetadata.JSON_PROPERTY_BUCKET_NAME,
  BucketGrantMetadata.JSON_PROPERTY_CREATOR,
  BucketGrantMetadata.JSON_PROPERTY_CREATION_DATE,
  BucketGrantMetadata.JSON_PROPERTY_MODIFICATION_HISTORY,
  BucketGrantMetadata.JSON_PROPERTY_BUCKET_ID,
  BucketGrantMetadata.JSON_PROPERTY_LINKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-26T11:53:55.670648-05:00[America/New_York]")
public class BucketGrantMetadata {
  public static final String JSON_PROPERTY_GRANTEE_TYPE = "granteeType";
  private String granteeType;

  public static final String JSON_PROPERTY_GRANTEE = "grantee";
  private String grantee;

  public static final String JSON_PROPERTY_ACCESS_TYPE = "accessType";
  private String accessType;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Integer priority;

  public static final String JSON_PROPERTY_BUCKET_NAME = "bucketName";
  private String bucketName;

  public static final String JSON_PROPERTY_CREATOR = "creator";
  private String creator;

  public static final String JSON_PROPERTY_CREATION_DATE = "creationDate";
  private Long creationDate;

  public static final String JSON_PROPERTY_MODIFICATION_HISTORY = "modificationHistory";
  private List<ModificationHistoryData> modificationHistory;

  public static final String JSON_PROPERTY_BUCKET_ID = "bucketId";
  private Long bucketId;

  public static final String JSON_PROPERTY_LINKS = "links";
  private List<Link> links;

  public BucketGrantMetadata() { 
  }

  public BucketGrantMetadata granteeType(String granteeType) {
    this.granteeType = granteeType;
    return this;
  }

   /**
   * Get granteeType
   * @return granteeType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRANTEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGranteeType() {
    return granteeType;
  }


  @JsonProperty(JSON_PROPERTY_GRANTEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGranteeType(String granteeType) {
    this.granteeType = granteeType;
  }


  public BucketGrantMetadata grantee(String grantee) {
    this.grantee = grantee;
    return this;
  }

   /**
   * Get grantee
   * @return grantee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRANTEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrantee() {
    return grantee;
  }


  @JsonProperty(JSON_PROPERTY_GRANTEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrantee(String grantee) {
    this.grantee = grantee;
  }


  public BucketGrantMetadata accessType(String accessType) {
    this.accessType = accessType;
    return this;
  }

   /**
   * Get accessType
   * @return accessType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessType() {
    return accessType;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessType(String accessType) {
    this.accessType = accessType;
  }


  public BucketGrantMetadata priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public BucketGrantMetadata bucketName(String bucketName) {
    this.bucketName = bucketName;
    return this;
  }

   /**
   * Get bucketName
   * @return bucketName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUCKET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBucketName() {
    return bucketName;
  }


  @JsonProperty(JSON_PROPERTY_BUCKET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBucketName(String bucketName) {
    this.bucketName = bucketName;
  }


  public BucketGrantMetadata creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreator() {
    return creator;
  }


  @JsonProperty(JSON_PROPERTY_CREATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreator(String creator) {
    this.creator = creator;
  }


  public BucketGrantMetadata creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreationDate() {
    return creationDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }


  public BucketGrantMetadata modificationHistory(List<ModificationHistoryData> modificationHistory) {
    this.modificationHistory = modificationHistory;
    return this;
  }

  public BucketGrantMetadata addModificationHistoryItem(ModificationHistoryData modificationHistoryItem) {
    if (this.modificationHistory == null) {
      this.modificationHistory = new ArrayList<>();
    }
    this.modificationHistory.add(modificationHistoryItem);
    return this;
  }

   /**
   * Get modificationHistory
   * @return modificationHistory
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFICATION_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModificationHistoryData> getModificationHistory() {
    return modificationHistory;
  }


  @JsonProperty(JSON_PROPERTY_MODIFICATION_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModificationHistory(List<ModificationHistoryData> modificationHistory) {
    this.modificationHistory = modificationHistory;
  }


  public BucketGrantMetadata bucketId(Long bucketId) {
    this.bucketId = bucketId;
    return this;
  }

   /**
   * Get bucketId
   * @return bucketId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUCKET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBucketId() {
    return bucketId;
  }


  @JsonProperty(JSON_PROPERTY_BUCKET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBucketId(Long bucketId) {
    this.bucketId = bucketId;
  }


  public BucketGrantMetadata links(List<Link> links) {
    this.links = links;
    return this;
  }

  public BucketGrantMetadata addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(List<Link> links) {
    this.links = links;
  }


  /**
   * Return true if this BucketGrantMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BucketGrantMetadata bucketGrantMetadata = (BucketGrantMetadata) o;
    return Objects.equals(this.granteeType, bucketGrantMetadata.granteeType) &&
        Objects.equals(this.grantee, bucketGrantMetadata.grantee) &&
        Objects.equals(this.accessType, bucketGrantMetadata.accessType) &&
        Objects.equals(this.priority, bucketGrantMetadata.priority) &&
        Objects.equals(this.bucketName, bucketGrantMetadata.bucketName) &&
        Objects.equals(this.creator, bucketGrantMetadata.creator) &&
        Objects.equals(this.creationDate, bucketGrantMetadata.creationDate) &&
        Objects.equals(this.modificationHistory, bucketGrantMetadata.modificationHistory) &&
        Objects.equals(this.bucketId, bucketGrantMetadata.bucketId) &&
        Objects.equals(this.links, bucketGrantMetadata.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(granteeType, grantee, accessType, priority, bucketName, creator, creationDate, modificationHistory, bucketId, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BucketGrantMetadata {\n");
    sb.append("    granteeType: ").append(toIndentedString(granteeType)).append("\n");
    sb.append("    grantee: ").append(toIndentedString(grantee)).append("\n");
    sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    bucketName: ").append(toIndentedString(bucketName)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    modificationHistory: ").append(toIndentedString(modificationHistory)).append("\n");
    sb.append("    bucketId: ").append(toIndentedString(bucketId)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

