/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * The version of the OpenAPI document: 1.0\"
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ow2.proactive.catalog.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.ow2.proactive.catalog.client.model.JobVariable;
import org.ow2.proactive.catalog.client.model.Link;
import org.ow2.proactive.catalog.client.model.Metadata;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.ow2.proactive.catalog.client.JSON;


/**
 * CatalogObjectMetadata
 */
@JsonPropertyOrder({
  CatalogObjectMetadata.JSON_PROPERTY_NAME,
  CatalogObjectMetadata.JSON_PROPERTY_EXTENSION,
  CatalogObjectMetadata.JSON_PROPERTY_LINKS,
  CatalogObjectMetadata.JSON_PROPERTY_COMMIT_TIME_RAW,
  CatalogObjectMetadata.JSON_PROPERTY_KIND,
  CatalogObjectMetadata.JSON_PROPERTY_BUCKET_NAME,
  CatalogObjectMetadata.JSON_PROPERTY_PROJECT_NAME,
  CatalogObjectMetadata.JSON_PROPERTY_TAGS,
  CatalogObjectMetadata.JSON_PROPERTY_COMMIT_TIME,
  CatalogObjectMetadata.JSON_PROPERTY_CONTENT_TYPE,
  CatalogObjectMetadata.JSON_PROPERTY_COMMIT_MESSAGE,
  CatalogObjectMetadata.JSON_PROPERTY_USERNAME,
  CatalogObjectMetadata.JSON_PROPERTY_OBJECT_KEY_VALUES,
  CatalogObjectMetadata.JSON_PROPERTY_VARIABLES_ORDER,
  CatalogObjectMetadata.JSON_PROPERTY_RIGHTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-12T10:49:33.729424-05:00[America/New_York]")
public class CatalogObjectMetadata {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  private String extension;

  public static final String JSON_PROPERTY_LINKS = "links";
  private List<Link> links;

  public static final String JSON_PROPERTY_COMMIT_TIME_RAW = "commit_time_raw";
  private String commitTimeRaw;

  public static final String JSON_PROPERTY_KIND = "kind";
  private String kind;

  public static final String JSON_PROPERTY_BUCKET_NAME = "bucket_name";
  private String bucketName;

  public static final String JSON_PROPERTY_PROJECT_NAME = "project_name";
  private String projectName;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private String tags;

  public static final String JSON_PROPERTY_COMMIT_TIME = "commit_time";
  private LocalDateTime commitTime;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "content_type";
  private String contentType;

  public static final String JSON_PROPERTY_COMMIT_MESSAGE = "commit_message";
  private String commitMessage;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_OBJECT_KEY_VALUES = "object_key_values";
  private List<Metadata> objectKeyValues;

  public static final String JSON_PROPERTY_VARIABLES_ORDER = "variables_order";
  private Map<String, Map<String, JobVariable>> variablesOrder = new HashMap<>();

  public static final String JSON_PROPERTY_RIGHTS = "rights";
  private String rights;

  public CatalogObjectMetadata() { 
  }

  public CatalogObjectMetadata name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public CatalogObjectMetadata extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Get extension
   * @return extension
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(String extension) {
    this.extension = extension;
  }


  public CatalogObjectMetadata links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CatalogObjectMetadata addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(List<Link> links) {
    this.links = links;
  }


  public CatalogObjectMetadata commitTimeRaw(String commitTimeRaw) {
    this.commitTimeRaw = commitTimeRaw;
    return this;
  }

   /**
   * Get commitTimeRaw
   * @return commitTimeRaw
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMIT_TIME_RAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommitTimeRaw() {
    return commitTimeRaw;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_TIME_RAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitTimeRaw(String commitTimeRaw) {
    this.commitTimeRaw = commitTimeRaw;
  }


  public CatalogObjectMetadata kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(String kind) {
    this.kind = kind;
  }


  public CatalogObjectMetadata bucketName(String bucketName) {
    this.bucketName = bucketName;
    return this;
  }

   /**
   * Get bucketName
   * @return bucketName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUCKET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBucketName() {
    return bucketName;
  }


  @JsonProperty(JSON_PROPERTY_BUCKET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBucketName(String bucketName) {
    this.bucketName = bucketName;
  }


  public CatalogObjectMetadata projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectName() {
    return projectName;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }


  public CatalogObjectMetadata tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(String tags) {
    this.tags = tags;
  }


  public CatalogObjectMetadata commitTime(LocalDateTime commitTime) {
    this.commitTime = commitTime;
    return this;
  }

   /**
   * Get commitTime
   * @return commitTime
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getCommitTime() {
    return commitTime;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitTime(LocalDateTime commitTime) {
    this.commitTime = commitTime;
  }


  public CatalogObjectMetadata contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentType() {
    return contentType;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public CatalogObjectMetadata commitMessage(String commitMessage) {
    this.commitMessage = commitMessage;
    return this;
  }

   /**
   * Get commitMessage
   * @return commitMessage
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommitMessage() {
    return commitMessage;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitMessage(String commitMessage) {
    this.commitMessage = commitMessage;
  }


  public CatalogObjectMetadata username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public CatalogObjectMetadata objectKeyValues(List<Metadata> objectKeyValues) {
    this.objectKeyValues = objectKeyValues;
    return this;
  }

  public CatalogObjectMetadata addObjectKeyValuesItem(Metadata objectKeyValuesItem) {
    if (this.objectKeyValues == null) {
      this.objectKeyValues = new ArrayList<>();
    }
    this.objectKeyValues.add(objectKeyValuesItem);
    return this;
  }

   /**
   * Get objectKeyValues
   * @return objectKeyValues
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT_KEY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Metadata> getObjectKeyValues() {
    return objectKeyValues;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_KEY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectKeyValues(List<Metadata> objectKeyValues) {
    this.objectKeyValues = objectKeyValues;
  }


  public CatalogObjectMetadata variablesOrder(Map<String, Map<String, JobVariable>> variablesOrder) {
    this.variablesOrder = variablesOrder;
    return this;
  }

  public CatalogObjectMetadata putVariablesOrderItem(String key, Map<String, JobVariable> variablesOrderItem) {
    if (this.variablesOrder == null) {
      this.variablesOrder = new HashMap<>();
    }
    this.variablesOrder.put(key, variablesOrderItem);
    return this;
  }

   /**
   * Get variablesOrder
   * @return variablesOrder
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VARIABLES_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Map<String, JobVariable>> getVariablesOrder() {
    return variablesOrder;
  }


  @JsonProperty(JSON_PROPERTY_VARIABLES_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariablesOrder(Map<String, Map<String, JobVariable>> variablesOrder) {
    this.variablesOrder = variablesOrder;
  }


  public CatalogObjectMetadata rights(String rights) {
    this.rights = rights;
    return this;
  }

   /**
   * Get rights
   * @return rights
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRights() {
    return rights;
  }


  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRights(String rights) {
    this.rights = rights;
  }


  /**
   * Return true if this CatalogObjectMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogObjectMetadata catalogObjectMetadata = (CatalogObjectMetadata) o;
    return Objects.equals(this.name, catalogObjectMetadata.name) &&
        Objects.equals(this.extension, catalogObjectMetadata.extension) &&
        Objects.equals(this.links, catalogObjectMetadata.links) &&
        Objects.equals(this.commitTimeRaw, catalogObjectMetadata.commitTimeRaw) &&
        Objects.equals(this.kind, catalogObjectMetadata.kind) &&
        Objects.equals(this.bucketName, catalogObjectMetadata.bucketName) &&
        Objects.equals(this.projectName, catalogObjectMetadata.projectName) &&
        Objects.equals(this.tags, catalogObjectMetadata.tags) &&
        Objects.equals(this.commitTime, catalogObjectMetadata.commitTime) &&
        Objects.equals(this.contentType, catalogObjectMetadata.contentType) &&
        Objects.equals(this.commitMessage, catalogObjectMetadata.commitMessage) &&
        Objects.equals(this.username, catalogObjectMetadata.username) &&
        Objects.equals(this.objectKeyValues, catalogObjectMetadata.objectKeyValues) &&
        Objects.equals(this.variablesOrder, catalogObjectMetadata.variablesOrder) &&
        Objects.equals(this.rights, catalogObjectMetadata.rights);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, extension, links, commitTimeRaw, kind, bucketName, projectName, tags, commitTime, contentType, commitMessage, username, objectKeyValues, variablesOrder, rights);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogObjectMetadata {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    commitTimeRaw: ").append(toIndentedString(commitTimeRaw)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    bucketName: ").append(toIndentedString(bucketName)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    commitTime: ").append(toIndentedString(commitTime)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    objectKeyValues: ").append(toIndentedString(objectKeyValues)).append("\n");
    sb.append("    variablesOrder: ").append(toIndentedString(variablesOrder)).append("\n");
    sb.append("    rights: ").append(toIndentedString(rights)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

