/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ow2.proactive.catalog.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.ow2.proactive.catalog.client.model.Link;

/**
 * CatalogObjectGrantMetadata
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-26T13:34:24.732+01:00")
public class CatalogObjectGrantMetadata {
  @JsonProperty("accessType")
  private String accessType = null;

  @JsonProperty("catalogObjectBucketId")
  private Long catalogObjectBucketId = null;

  @JsonProperty("catalogObjectId")
  private Long catalogObjectId = null;

  @JsonProperty("creator")
  private String creator = null;

  @JsonProperty("grantee")
  private String grantee = null;

  @JsonProperty("granteeType")
  private String granteeType = null;

  @JsonProperty("links")
  private List<Link> links = null;

  public CatalogObjectGrantMetadata accessType(String accessType) {
    this.accessType = accessType;
    return this;
  }

   /**
   * Get accessType
   * @return accessType
  **/
  @ApiModelProperty(value = "")
  public String getAccessType() {
    return accessType;
  }

  public void setAccessType(String accessType) {
    this.accessType = accessType;
  }

  public CatalogObjectGrantMetadata catalogObjectBucketId(Long catalogObjectBucketId) {
    this.catalogObjectBucketId = catalogObjectBucketId;
    return this;
  }

   /**
   * Get catalogObjectBucketId
   * @return catalogObjectBucketId
  **/
  @ApiModelProperty(value = "")
  public Long getCatalogObjectBucketId() {
    return catalogObjectBucketId;
  }

  public void setCatalogObjectBucketId(Long catalogObjectBucketId) {
    this.catalogObjectBucketId = catalogObjectBucketId;
  }

  public CatalogObjectGrantMetadata catalogObjectId(Long catalogObjectId) {
    this.catalogObjectId = catalogObjectId;
    return this;
  }

   /**
   * Get catalogObjectId
   * @return catalogObjectId
  **/
  @ApiModelProperty(value = "")
  public Long getCatalogObjectId() {
    return catalogObjectId;
  }

  public void setCatalogObjectId(Long catalogObjectId) {
    this.catalogObjectId = catalogObjectId;
  }

  public CatalogObjectGrantMetadata creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @ApiModelProperty(value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public CatalogObjectGrantMetadata grantee(String grantee) {
    this.grantee = grantee;
    return this;
  }

   /**
   * Get grantee
   * @return grantee
  **/
  @ApiModelProperty(value = "")
  public String getGrantee() {
    return grantee;
  }

  public void setGrantee(String grantee) {
    this.grantee = grantee;
  }

  public CatalogObjectGrantMetadata granteeType(String granteeType) {
    this.granteeType = granteeType;
    return this;
  }

   /**
   * Get granteeType
   * @return granteeType
  **/
  @ApiModelProperty(value = "")
  public String getGranteeType() {
    return granteeType;
  }

  public void setGranteeType(String granteeType) {
    this.granteeType = granteeType;
  }

  public CatalogObjectGrantMetadata links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CatalogObjectGrantMetadata addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogObjectGrantMetadata catalogObjectGrantMetadata = (CatalogObjectGrantMetadata) o;
    return Objects.equals(this.accessType, catalogObjectGrantMetadata.accessType) &&
        Objects.equals(this.catalogObjectBucketId, catalogObjectGrantMetadata.catalogObjectBucketId) &&
        Objects.equals(this.catalogObjectId, catalogObjectGrantMetadata.catalogObjectId) &&
        Objects.equals(this.creator, catalogObjectGrantMetadata.creator) &&
        Objects.equals(this.grantee, catalogObjectGrantMetadata.grantee) &&
        Objects.equals(this.granteeType, catalogObjectGrantMetadata.granteeType) &&
        Objects.equals(this.links, catalogObjectGrantMetadata.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessType, catalogObjectBucketId, catalogObjectId, creator, grantee, granteeType, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogObjectGrantMetadata {\n");
    
    sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
    sb.append("    catalogObjectBucketId: ").append(toIndentedString(catalogObjectBucketId)).append("\n");
    sb.append("    catalogObjectId: ").append(toIndentedString(catalogObjectId)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    grantee: ").append(toIndentedString(grantee)).append("\n");
    sb.append("    granteeType: ").append(toIndentedString(granteeType)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

