/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ow2.proactive.catalog.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.ow2.proactive.catalog.client.model.DependsOnCatalogObject;

/**
 * CatalogObjectDependencies
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-16T15:29:25.212+01:00")
public class CatalogObjectDependencies {
  @JsonProperty("called_by")
  private List<String> calledBy = null;

  @JsonProperty("depends_on")
  private List<DependsOnCatalogObject> dependsOn = null;

  public CatalogObjectDependencies calledBy(List<String> calledBy) {
    this.calledBy = calledBy;
    return this;
  }

  public CatalogObjectDependencies addCalledByItem(String calledByItem) {
    if (this.calledBy == null) {
      this.calledBy = new ArrayList<>();
    }
    this.calledBy.add(calledByItem);
    return this;
  }

   /**
   * Get calledBy
   * @return calledBy
  **/
  @ApiModelProperty(value = "")
  public List<String> getCalledBy() {
    return calledBy;
  }

  public void setCalledBy(List<String> calledBy) {
    this.calledBy = calledBy;
  }

  public CatalogObjectDependencies dependsOn(List<DependsOnCatalogObject> dependsOn) {
    this.dependsOn = dependsOn;
    return this;
  }

  public CatalogObjectDependencies addDependsOnItem(DependsOnCatalogObject dependsOnItem) {
    if (this.dependsOn == null) {
      this.dependsOn = new ArrayList<>();
    }
    this.dependsOn.add(dependsOnItem);
    return this;
  }

   /**
   * Get dependsOn
   * @return dependsOn
  **/
  @ApiModelProperty(value = "")
  public List<DependsOnCatalogObject> getDependsOn() {
    return dependsOn;
  }

  public void setDependsOn(List<DependsOnCatalogObject> dependsOn) {
    this.dependsOn = dependsOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogObjectDependencies catalogObjectDependencies = (CatalogObjectDependencies) o;
    return Objects.equals(this.calledBy, catalogObjectDependencies.calledBy) &&
        Objects.equals(this.dependsOn, catalogObjectDependencies.dependsOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calledBy, dependsOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogObjectDependencies {\n");
    
    sb.append("    calledBy: ").append(toIndentedString(calledBy)).append("\n");
    sb.append("    dependsOn: ").append(toIndentedString(dependsOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

