/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ow2.proactive.catalog.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModificationHistoryData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-01T22:20:45.340+02:00")
public class ModificationHistoryData {
  @JsonProperty("changes")
  private String changes = null;

  @JsonProperty("modificationDate")
  private Long modificationDate = null;

  @JsonProperty("newValues")
  private String newValues = null;

  @JsonProperty("oldValues")
  private String oldValues = null;

  @JsonProperty("username")
  private String username = null;

  public ModificationHistoryData changes(String changes) {
    this.changes = changes;
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(value = "")
  public String getChanges() {
    return changes;
  }

  public void setChanges(String changes) {
    this.changes = changes;
  }

  public ModificationHistoryData modificationDate(Long modificationDate) {
    this.modificationDate = modificationDate;
    return this;
  }

   /**
   * Get modificationDate
   * @return modificationDate
  **/
  @ApiModelProperty(value = "")
  public Long getModificationDate() {
    return modificationDate;
  }

  public void setModificationDate(Long modificationDate) {
    this.modificationDate = modificationDate;
  }

  public ModificationHistoryData newValues(String newValues) {
    this.newValues = newValues;
    return this;
  }

   /**
   * Get newValues
   * @return newValues
  **/
  @ApiModelProperty(value = "")
  public String getNewValues() {
    return newValues;
  }

  public void setNewValues(String newValues) {
    this.newValues = newValues;
  }

  public ModificationHistoryData oldValues(String oldValues) {
    this.oldValues = oldValues;
    return this;
  }

   /**
   * Get oldValues
   * @return oldValues
  **/
  @ApiModelProperty(value = "")
  public String getOldValues() {
    return oldValues;
  }

  public void setOldValues(String oldValues) {
    this.oldValues = oldValues;
  }

  public ModificationHistoryData username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModificationHistoryData modificationHistoryData = (ModificationHistoryData) o;
    return Objects.equals(this.changes, modificationHistoryData.changes) &&
        Objects.equals(this.modificationDate, modificationHistoryData.modificationDate) &&
        Objects.equals(this.newValues, modificationHistoryData.newValues) &&
        Objects.equals(this.oldValues, modificationHistoryData.oldValues) &&
        Objects.equals(this.username, modificationHistoryData.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changes, modificationDate, newValues, oldValues, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModificationHistoryData {\n");
    
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    newValues: ").append(toIndentedString(newValues)).append("\n");
    sb.append("    oldValues: ").append(toIndentedString(oldValues)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

