/*
 * CatalogObjectEntity Catalog API
 * The purpose of the catalog is to store ProActive objects.  A catalog is subdivided into buckets.   Each bucket manages zero, one or more versioned ProActive objects.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.CatalogObjectMetadata;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CatalogObjectRevisionControllerApi
 */
@Ignore
public class CatalogObjectRevisionControllerApiTest {

    private final CatalogObjectRevisionControllerApi api = new CatalogObjectRevisionControllerApi();

    
    /**
     * Creates a new catalog object revision
     *
     */
    @Test
    public void createUsingPOST2Test() {
        String bucketName = null;
        String name = null;
        String commitMessage = null;
        File file = null;
        String sessionID = null;
        CatalogObjectMetadata response = api.createUsingPOST2(bucketName, name, commitMessage, file, sessionID);

        // TODO: test validations
    }
    
    /**
     * Gets the raw content of a specific revision
     *
     */
    @Test
    public void getRawUsingGET1Test() {
        String bucketName = null;
        String name = null;
        Long commitTime = null;
        String sessionID = null;
        File response = api.getRawUsingGET1(bucketName, name, commitTime, sessionID);

        // TODO: test validations
    }
    
    /**
     * Gets a specific revision
     *
     */
    @Test
    public void getUsingGET1Test() {
        String bucketName = null;
        String name = null;
        Long commitTime = null;
        String sessionID = null;
        CatalogObjectMetadata response = api.getUsingGET1(bucketName, name, commitTime, sessionID);

        // TODO: test validations
    }
    
    /**
     * Lists a catalog object revisions
     *
     */
    @Test
    public void listUsingGET2Test() {
        String bucketName = null;
        String name = null;
        String sessionID = null;
        List<CatalogObjectMetadata> response = api.listUsingGET2(bucketName, name, sessionID);

        // TODO: test validations
    }
    
}
